FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["FollowService.Api/FollowService.Api.csproj", "FollowService.Api/"]
RUN dotnet restore "FollowService.Api/FollowService.Api.csproj"
COPY . .
WORKDIR "/src/FollowService.Api"
RUN dotnet build "FollowService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FollowService.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:10000
ENV PORT=10000
ENTRYPOINT ["dotnet", "FollowService.Api.dll"]