FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["PostService.Api/PostService.Api.csproj", "PostService.Api/"]
RUN dotnet restore "PostService.Api/PostService.Api.csproj"
COPY . .
WORKDIR "/src/PostService.Api"
RUN dotnet build "PostService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PostService.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "PostService.Api.dll"]